{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-podmonitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with .Values.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      role: {{ .Values.proxy.role }}
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
{{- end }}
