# Kupo Operator values
replicaCount: 1
image:
  repository: ghcr.io/demeter-run/ext-cardano-kupo-operator
  tag: latest
  pullPolicy: IfNotPresent

# Environment configuration
prometheusUrl: "http://prometheus-operated.mynamspace.svc.cluster.local:9090/api/v1"
metricsDelay: "60"

apiKeySalt: "change-me"
defaultKupoVersion: "v2"
dnsZone: "example.com"
extensionSubdomain: "kupo.example.com"

# DCU per request configuration
perRequestDcus:
  mainnet: "10"
  preprod: "5"
  preview: "5"
  sanchonet: "5"
  default: "5"

resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"
tolerations: []
# Example tolerations:
# - key: "key"
#   operator: "Equal"
#   value: "value"
#   effect: "NoSchedule"
affinity: {}

podMonitor:
  enabled: false
  labels: {}

serviceAccount:
  annotations: {}
  name: "kupo-operator"
