apiVersion: v2
name: ext-ogmios-operator
description: Extention Ogmios operator
version: 0.0.1
appVersion: "0.0.1"

sources:
  - https://github.com/demeter-run/ext-cardano-ogmios

maintainers:
  - name: aurora
    email: aurora@blinklabs.io
  - name: overcookedpanda
    email: overcookedpanda@blinklabs.io
  - name: verbotenj
    email: verbotenj@blinklabs.io
  - name: wolf31o2
    email: wolf31o2@blinklabs.io
