apiVersion: v2
name: ergo-node
description: Ergo protocol description & reference client implementation
version: 0.3.5
appVersion: "v6.1.6"
maintainers:
  - name: wolf31o2
    email: wolf31o2@blinklabs.io
