{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
{{ include "tx-submit-api-mirror.labels" . | indent 4 }}
  name: {{ include "tx-submit-api-mirror.fullname" . }}
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ include "tx-submit-api-mirror.fullname" . }}
            port:
              number: 8090
        path: /api
        pathType: Prefix
{{- if hasKey .Values.ingress "host" }}
    host: {{ .Values.ingress.host }}
{{- end }}
{{- end }}
