---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "tx-submit-api-mirror.fullname" . }}
{{ include "tx-submit-api-mirror.labels" . | indent 4 }}
  name: {{ include "tx-submit-api-mirror.fullname" . }}
spec:
  ports:
  - name: tx-submit-api-mirror
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    cardano_network: {{ .Values.cardano_network }}
    app.kubernetes.io/name: {{ include "tx-submit-api-mirror.fullname" . }}
  sessionAffinity: ClientIP
  type: ClusterIP
