{{ if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.annotations }}
  annotations: {{ toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  labels:
    cardano_network: {{ .Values.cardano_network }}
{{ include "ogmios.labels" . | indent 4 }}
  name: {{ include "ogmios.fullname" . }}
spec:
  ports: {{ toYaml .Values.service.ports | nindent 2 }}
  selector: {{ include "ogmios.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
  type: {{ .Values.service.type }}
{{- end }}
