{{- range $idx, $config := .Values.configFiles }}
{{-   if ($config.secret | default false) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvpn.fullname" $ }}-config-{{ $idx }}
  labels:
    {{- include "openvpn.labels" $ | nindent 4 }}
type: Opaque
data:
  "{{ $config.name }}": {{ $config.content | b64enc }}
{{-   else if $config.content }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openvpn.fullname" $ }}-config-{{ $idx }}
  labels:
    {{- include "openvpn.labels" $ | nindent 4 }}
data:
  "{{ $config.name }}": |-
    {{- $config.content | nindent 4 }}
{{-   end }}
{{- end }}

{{- if .Values.startupScript }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openvpn.fullname" $ }}-config-startup-script
  labels:
    {{- include "openvpn.labels" $ | nindent 4 }}
data:
  "entrypoint-user.sh": |-
    {{- .Values.startupScript | nindent 4 }}
{{- end }}
