apiVersion: v1
kind: Service
metadata:
  name: {{ include "openvpn.fullname" . }}
  labels:
    {{- include "openvpn.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ovpn
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
      protocol: {{ .Values.service.protocol }}
      name: ovpn
  selector:
    {{- include "openvpn.selectorLabels" . | nindent 4 }}
  {{- with .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
