{{- range $name, $data := .Values.roleBindings }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
  {{- with $data.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $data.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ default "Role" $data.roleKind }}
  name: {{ required (printf "Values.roleBindings.%s.roleName is required" $name) $data.roleName }}
subjects:
  {{- toYaml (default (list) $data.subjects) | nindent 2 }}
{{- end }}
