{{- range $name, $data := .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  {{- with $data.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $data.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if hasKey $data "automountServiceAccountToken" }}
automountServiceAccountToken: {{ $data.automountServiceAccountToken }}
{{- end }}
{{- with $data.imagePullSecrets }}
imagePullSecrets:
{{-   range . }}
  - name: {{ . }}
{{-   end }}
{{- end }}

{{- if $data.createToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  annotations:
    kubernetes.io/service-account.name: {{ $name }}
type: kubernetes.io/service-account-token
{{- end }}
{{- end }}
