---
cardano_network: preview
cardano_node:
  host: cardano-node-headless
  port: 30000
  skip_check: true
image:
  repository: ghcr.io/blinklabs-io/cardano-node-api
  tag: 0.7.0
replicaCount: 1
resources: {}
tolerations:
- effect: NoSchedule
  key: kubernetes.io/arch
  operator: Equal
  value: arm64

affinity: {}

ingress:
  enabled: false
  cluster_issuer: letsencrypt-dns01
  host: node-api.preview.dmtr.host
  ingressClassName: kong

service:
  annotations: {}
  ports:
    - name: grpc
      port: 443
      protocol: TCP
      targetPort: 9090
  # type: ClusterIP
  type: LoadBalancer

secret:
  enabled: false
  tlsKey: ""
  tlsCrt: ""
