---
nameOverride: ""

cardano_network: preview
cardano_node:
  host: cardano-node-headless
  port: 30000
  skip_check: true
image:
  repository: ghcr.io/blinklabs-io/cardano-node-api
  tag: 0.7.0
replicaCount: 1
resources: {}
tolerations:
- key: kubernetes.io/arch
  operator: Equal
  value: arm64
  effect: NoSchedule

affinity: {}

ingress:
  enabled: false
  host: node-api.preview.local
  ingressClassName: kong

service:
  enabled: false
  annotations: {}
  ports:
    - name: grpc
      port: 443
      protocol: TCP
      targetPort: 9090
  type: LoadBalancer

# Example of a ClusterIP service
  # ports:
  # - name: api
  #   port: 8080
  #   protocol: TCP
  #   targetPort: 8080
  # type: ClusterIP

secret:
  enabled: false
  # tlsKey: ""
  # tlsCrt: ""
