apiVersion: v1
name: cardano-dbsync
description: Deploys a Cardano DB Sync service
version: 0.0.2
appVersion: v13.6.0.4
maintainers:
  - name: aurora
    email: aurora@blinklabs.io
  - name: overcookedpanda
    email: overcookedpanda@blinklabs.io
  - name: verbotenj
    email: verbotenj@blinklabs.io
  - name: wolf31o2
    email: wolf31o2@blinklabs.io
