# fullnameOverride: cardano-db-sync
# nameOverride: cardano-db-sync

cardano_network: mainnet

cardano_node:
  host: backbone.mainnet.cardanofoundation.org
  port: 3001

image:
  repository: ghcr.io/blinklabs-io/cardano-db-sync
  tag: 13.6.0.5

environment: {}
  # Additional environments can be set here

common_env:
# MAINNET ONLY
# If set to true it will try to find latest snapshot and restore it on first run
# https://update-cardano-mainnet.iohk.io/cardano-db-sync/index.html#
  RESTORE_SNAPSHOT: false
  POSTGRES_DB: dbsync_mainnet
  # POSTGRES_HOST: postgres-dbsync-mainnet.dbsync.svc.cluster.local
  # POSTGRES_HOST_RO: postgres-dbsync-mainnet-repl.dbsync.svc.cluster.local
  # POSTGRES_HOST_RW: postgres-dbsync-mainnet.dbsync.svc.cluster.local
  # POSTGRES_PORT: "5432"

# https://github.com/IntersectMBO/cardano-db-sync/tree/master?tab=readme-ov-file#storage
volume:
  size: 350Gi
  storageClassName: hyperdisk-balanced

updateStrategy:
  type: RollingUpdate

metrics:
  enabled: false
  # If port is specified it will use port number
  # instead of the default "metrics" port name.
  # port: 8080
  serviceMonitor:
    enabled: true
    namespace: monitoring

resources: {}
  # limits:
  #   cpu: 2000m
  #   memory: 4Gi
  # requests:
  #   cpu: 100m
  #   memory: 2Gi

affinity: {}

tolerations: {}

postgres:
  # Super user credentials
  userSecret:
    name: postgres.dbsync-mainnet
    key: username
  passwordSecret:
    name: postgres.dbsync-mainnet
    key: password
  # Read-only user credentials
  roUserSecret:
    name: app.dbsync-mainnet
    key: username
  roPasswordSecret:
    name: app.dbsync-mainnet
    key: password
