apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: baliusworkers.demeter.run
spec:
  group: demeter.run
  names:
    categories:
      - demeter-worker
    kind: BaliusWorker
    plural: baliusworkers
    shortNames:
      - bwapts
    singular: baliusworker
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Active
          type: boolean
          jsonPath: .spec.active
        - name: Display Name
          type: string
          jsonPath: .spec.displayName
        - name: Network
          type: string
          jsonPath: .spec.network
        - name: Throughput Tier
          type: string
          jsonPath: .spec.throughputTier
        - name: Endpoint URL
          type: string
          jsonPath: .status.endpointUrl
        - name: Authenticated Endpoint URL
          type: string
          jsonPath: .status.authenticatedEndpointUrl
        - name: Auth Token
          type: string
          jsonPath: .status.authToken
      schema:
        openAPIV3Schema:
          title: BaliusWorker
          description: Auto-generated derived type for BaliusWorkerSpec via `CustomResource`
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - authToken
                - config
                - displayName
                - network
                - throughputTier
                - url
                - version
              properties:
                active:
                  type: boolean
                  nullable: true
                authToken:
                  type: string
                config:
                  type: object
                  additionalProperties: true
                displayName:
                  type: string
                network:
                  type: string
                throughputTier:
                  type: string
                url:
                  type: string
                version:
                  type: string
            status:
              type: object
              nullable: true
              required:
                - authToken
                - endpointUrl
              properties:
                authToken:
                  type: string
                authenticatedEndpointUrl:
                  type: string
                  nullable: true
                endpointUrl:
                  type: string
                error:
                  type: string
                  nullable: true
      subresources:
        status: {}
