replicaCount: 1

image:
  repository: ghcr.io/blinklabs-io/bursa
  tag: "main"
  pullPolicy: IfNotPresent

environment:
  NETWORK: "mainnet"

service:
  annotations: {}
  type: ClusterIP
  ports:
    api: 8080
    metrics: 8081
