replicaCount: 1

image:
  repository: ghcr.io/blinklabs-io/bursa
  tag: "0.10.0"
  pullPolicy: IfNotPresent

environment:
  CARDANO_NETWORK: "mainnet"
  # Optional variables. Uncomment and set to use.
  # API_LISTEN_ADDRESS: ""
  # API_LISTEN_PORT: 8080
  # GOOGLE_PROJECT: ""
  # GCP_KMS_RESOURCE_ID: ""
  # GCP_SECRET_PREFIX: ""
  # LOGGING_LEVEL: "info"
  # METRICS_LISTEN_ADDRESS: ""
  # METRICS_LISTEN_PORT: 8081

service:
  annotations: {}
  type: ClusterIP
  ports:
    api: 8080
    metrics: 8081

serviceAccount:
  name: kms-sa
  annotations: {}
    # iam.gke.io/gcp-service-account: bursa-sa@example-google-project.iam.gserviceaccount.com

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

tolerations: []
