apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ergo-node.fullname" . }}-config
  labels:
    {{- include "ergo-node.labels" . | nindent 4 }}
data:
  ergo.conf: |
    ergo {
      node {
        mining = {{ .Values.ergo.node.mining }}
        extraIndex = {{ .Values.ergo.node.extraIndex }}
        stateType = "{{ .Values.ergo.node.stateType }}"
        verifyTransactions = {{ .Values.ergo.node.verifyTransactions }}
        blocksToKeep = {{ .Values.ergo.node.blocksToKeep }}

        utxo {
          utxoBootstrap = {{ .Values.ergo.node.utxo.utxoBootstrap }}
          storingUtxoSnapshots = {{ .Values.ergo.node.utxo.storingUtxoSnapshots }}
          p2pUtxoSnapshots = {{ .Values.ergo.node.utxo.p2pUtxoSnapshots }}
        }

        nipopow {
          nipopowBootstrap = {{ .Values.ergo.node.nipopow.nipopowBootstrap }}
          p2pNipopows = {{ .Values.ergo.node.nipopow.p2pNipopows }}
        }
      }
    }

    scorex {
      restApi {
        {{- if and .Values.scorex.restApi.publicUrl (ne .Values.scorex.restApi.publicUrl "") }}
        publicUrl = "{{ .Values.scorex.restApi.publicUrl }}"
        {{- end }}
        apiKeyHash = "{{ .Values.scorex.restApi.apiKeyHash }}"
        {{- if .Values.scorex.restApi.cors }}
        cors = [
        {{- range $index, $origin := .Values.scorex.restApi.cors }}
          "{{ $origin }}"{{- if not (eq (add1 $index) (len $.Values.scorex.restApi.cors)) }},{{ end }}
        {{- end }}
        ]
        {{- end }}
      }

      network {
        {{- if and .Values.scorex.network.declaredAddress (ne .Values.scorex.network.declaredAddress "") }}
        declaredAddress = "{{ .Values.scorex.network.declaredAddress }}"
        {{- end }}
        nodeName = "{{ .Values.scorex.network.nodeName }}"
        {{- if and .Values.scorex.network.knownPeers (gt (len .Values.scorex.network.knownPeers) 0) }}
        knownPeers = [
        {{- range $index, $peer := .Values.scorex.network.knownPeers }}
          "{{ $peer }}"{{- if not (eq (add1 $index) (len $.Values.scorex.network.knownPeers)) }},{{ end }}
        {{- end }}
        ]
        {{- end }}
      }
    }
