---
apiVersion: v1
kind: Service
metadata:
  labels:
{{- include "ergo-node.labels" . | nindent 4 }}
  name: {{ include "ergo-node.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: p2p
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "ergo-node.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    ergo_network: {{ include "ergo-node.network" . }}
