---
apiVersion: v1
kind: Service
metadata:
  labels:
{{- include "ergo-node.labels" . | nindent 4 }}
  name: {{ include "ergo-node.fullname" . }}
  {{- with .Values.service.annotation }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: p2p
      protocol: TCP
  selector:
    {{- include "ergo-node.matchLabels" . | nindent 4 }}
