apiVersion: v1
name: ogmios
description: Creates an Ogmios API service with SOCAT sidecar
version: 0.0.3
appVersion: v6.12.0
maintainers:
  - name: aurora
    email: aurora@blinklabs.io
  - name: overcookedpanda
    email: overcookedpanda@blinklabs.io
  - name: verbotenj
    email: verbotenj@blinklabs.io
  - name: wolf31o2
    email: wolf31o2@blinklabs.io
