{{- if and .Values.balius.serviceAccount.create (ne .Values.balius.serviceAccount.name "default") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.balius.serviceAccount.name }}
rules:
  - apiGroups: ["", "demeter.run", "networking.k8s.io", "gateway.networking.k8s.io", "configuration.konghq.com", "coordination.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.balius.serviceAccount.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.balius.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.balius.serviceAccount.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
