apiVersion: v2
name: ext-proxy
description: A Helm chart for managing different proxy configurations for https://github.com/demeter-run
version: 0.0.3
appVersion: "0.0.1"

maintainers:
  - name: aurora
    email: aurora@blinklabs.io
  - name: overcookedpanda
    email: overcookedpanda@blinklabs.io
  - name: verbotenj
    email: verbotenj@blinklabs.io
  - name: wolf31o2
    email: wolf31o2@blinklabs.io
