---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cdnsd.fullname" . }}
  labels:
    {{- include "cdnsd.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cdnsd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cdnsd.selectorLabels" . | nindent 8 }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "cdnsd.serviceAccountName" . }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: cdnsd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.environment }}
          {{- if $value }}
          - name: {{ $key }}
            value: "{{ $value }}"
          {{- end }}
          {{- end }}
          ports:
            - name: dns-udp
              containerPort: {{ .Values.environment.DNS_LISTEN_PORT | default "8053" | int }}
              protocol: UDP
            - name: dns-tcp
              containerPort: {{ .Values.environment.DNS_LISTEN_PORT | default "8053" | int }}
              protocol: TCP
            - name: tls-tcp
              containerPort: {{ .Values.environment.DNS_LISTEN_TLS_PORT | default "8853" | int }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.environment.METRICS_LISTEN_PORT | default "8081" | int }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: "/data"
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "cdnsd.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}