{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cdnsd.fullname" . }}-metrics-monitor
  labels:
    {{- include "cdnsd.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "cdnsd.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.metrics.serviceMonitor.interval }}
    path: {{ .Values.metrics.serviceMonitor.path }}
    scheme: http
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}