---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.labels }}
  labels: {{- toYaml . | nindent 4 }}
  {{- end }}
spec: {{- toYaml .Values.spec | nindent 2 }}
