{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "handshake-node.network-fullname" . }}-metrics-monitor
  labels:
    app: {{ include "handshake-node.name" . }}
    {{- include "handshake-node.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      handshake_network: {{ include "handshake-node.network" . }}
      app.kubernetes.io/name: {{ include "handshake-node.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: metrics
  endpoints:
  - port: metrics
    interval: {{ .Values.metrics.serviceMonitor.interval }}
    path: {{ .Values.metrics.serviceMonitor.path }}
    scheme: http
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}