---
cardano_network: preview
cardano_node:
  host: cardano-node-headless
  port: 30000
  skip_check: true
image:
  repository: ghcr.io/blinklabs-io/tx-submit-api
  tag: 0.17.5
ingress:
  enabled: false
  host: submit-api.preview.local
replicaCount: 1
resources: {}
tolerations:
- key: kubernetes.io/arch
  operator: Equal
  value: arm64
  effect: NoSchedule
