apiVersion: v2
name: demeter-fabric
description: Demeter Fabric Daemon - Kafka-based monitoring daemon for Demeter platform
version: 0.1.0
appVersion: "0.1.0"

sources:
  - https://github.com/demeter-run/fabric

maintainers:
  - name: aurora
    email: aurora@blinklabs.io
  - name: verbotenj
    email: verbotenj@blinklabs.io
  - name: wolf31o2
    email: wolf31o2@blinklabs.io
