{{- if .Values.mnemonic }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName | default "bluefin-secret" }}
type: Opaque
data:
  MNEMONIC: {{ .Values.mnemonic | b64enc }}
{{- end }}
