apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bursa.fullname" . }}
  labels:
    {{- include "bursa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bursa.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bursa.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: bursa
          command: ["bursa", "api"]
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NETWORK
              value: {{ .Values.environment.NETWORK }}
          ports:
            - name: api
              containerPort: 8080
            - name: metrics
              containerPort: 8081
