apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bursa.fullname" . }}
  labels:
    {{- include "bursa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bursa.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bursa.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      containers:
      - name: bursa
        command: ["bursa", "api"]
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          {{- range $key, $value := .Values.environment }}
          {{- if $value }}
          - name: {{ $key }}
            value: "{{ $value }}"
          {{- end }}
          {{- end }}
        ports:
          - name: api
            containerPort: 8080
          - name: metrics
            containerPort: 8081
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
