---
{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "bursa.fullname" . }}
  labels:
    {{- include "bursa.labels" . | nindent 4 }}
{{- with .Values.podMonitor.extraLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bursa.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- with .Values.podMonitor.podTargetLabels }}
  podTargetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  podMetricsEndpoints:
    {{- if .Values.podMonitor.podMetricsEndpoints }}
    {{- toYaml .Values.podMonitor.podMetricsEndpoints | nindent 4 }}
    {{- else }}
    - port: metrics
      path: /metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
    {{- end }}
{{- end }}
