---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adder.fullname" . }}
  labels:
    {{- include "adder.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "adder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "adder.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ toYaml .Values.config | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: adder
          command: ["adder", "-config", "/adder/config.yaml"]
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.environment }}
          {{- if $value }}
          - name: {{ $key }}
            value: "{{ $value }}"
          {{- end }}
          {{- end }}
          ports:
            - name: webhook
              containerPort: 3000
              protocol: TCP
            - name: api
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /adder
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "adder.fullname" . }}-config
            items:
              - key: config
                path: config.yaml
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
