---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cardano-node-leios.fullname" . }}-topology
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cardano-node-leios.labels" . | indent 4 }}
data:
  topology.json: |
    {
      "bootstrapPeers": [{{- range $i, $peer := .Values.topology.bootstrapPeers }}
        {{- if $i }},{{ end }}
        { "address": {{ $peer.address | toJson }}, "port": {{ $peer.port }} }
      {{- end }}],
      "localRoots": [
      {{- range $i, $local := .Values.topology.localRoots }}
        {{- if $i }},{{ end }}
        {
          "accessPoints": [
          {{- range $j, $peer := $local.accessPoints }}
            {{- if $j }},{{ end }}
            { "address": {{ $peer.address | toJson }}, "port": {{ $peer.port }}, "name": {{ $peer.name | toJson }} }
          {{- end }}
          ],
          "advertise": {{ $local.advertise | default false | toJson }},
          "trustable": {{ $local.trustable | default false | toJson }},
          "valency": {{ $local.valency }}
        }
      {{- end }}
      ],
      "peerSnapshotFile": "peer-snapshot.json",
      "publicRoots": [],
      "useLedgerAfterSlot": {{ .Values.topology.useLedgerAfterSlot | int }}
    }
