---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cardano-node-leios.fullname" . }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{ include "cardano-node-leios.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: ntn
    port: {{ .Values.service.ports.ntn.port }}
    targetPort: {{ .Values.service.ports.ntn.targetPort }}
    protocol: TCP
  - name: metrics
    port: {{ .Values.service.ports.metrics.port }}
    targetPort: {{ .Values.service.ports.metrics.targetPort }}
    protocol: TCP
  selector:
{{ include "cardano-node-leios.matchLabels" . | indent 4 }}
