apiVersion: v2
name: bind9
description: "A Helm chart for deploying BIND9 DNS resolver"
version: 0.0.1
appVersion: "9.18"

sources:
  - https://github.com/blinklabs-io/charts

maintainers:
  - name: aurora
    email: aurora@blinklabs.io
  - name: verbotenj
    email: verbotenj@blinklabs.io
  - name: wolf31o2
    email: wolf31o2@blinklabs.io
  - name: overcookedpanda
    email: overcookedpanda@blinklabs.io
