---
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "cardano-node.labels" . | indent 4 }}
  name: {{ include "cardano-node.fullname" . }}-headless
spec:
  clusterIP: None
  ports:
  - name: ntn
    port: {{ .Values.service.ports.ntn.port }}
    protocol: TCP
    targetPort: {{ .Values.service.ports.ntn.targetPort }}
  selector:
    cardano_network: {{ include "cardano-node.network" . }}
    app.kubernetes.io/name: {{ include "cardano-node.fullname" . }}
  sessionAffinity: ClientIP
  type: ClusterIP
