---
{{- if .Values.topology.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cardano-node.fullname" . }}-topology
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
{{ include "cardano-node.labels" . | nindent 4 }}
data:
  topology.json: |-
{{ toJson .Values.topology.config | indent 4 }}
{{- end }}