---
{{- if .Values.topology.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cardano-node.fullname" . }}-topology
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
{{ include "cardano-node.labels" . | nindent 4 }}
data:
  topology.json: |
    {
      "bootstrapPeers": [{{- range $i, $peer := .Values.topology.bootstrapPeers }}
        {{- if $i }},{{ end }}
        { "address": {{ $peer.address | toJson }}, "port": {{ $peer.port }} }
      {{- end }}],
      "localRoots": [
      {{- range $i, $local := .Values.topology.localRoots }}
        {{- if $i }},{{ end }}
        {
          "accessPoints": [
          {{- range $j, $peer := $local.accessPoints }}
            {{- if $j }},{{ end }}
            { "address": {{ $peer.address | toJson }}, "port": {{ $peer.port }}, "name": {{ $peer.name | toJson }} }
          {{- end }}
          ],
          "advertise": {{ $local.advertise | toJson }},
          "trustable": {{ $local.trustable | default false | toJson }},
          "valency": {{ $local.valency }}
        }
      {{- end }}
      ]
      {{- with .Values.topology.peerSnapshotFile }},
      "peerSnapshotFile": {{ . | toJson }}
      {{- end }},
      "publicRoots": [{{- $publicIndex := 0 }}
      {{- range $public := .Values.topology.publicRoots }}
        {{- if and (hasKey $public "accessPoints") (gt (len $public.accessPoints) 0) }}
          {{- if gt $publicIndex 0 }},{{ end }}
          {
            "accessPoints": [{{- $peerIndex := 0 }}
            {{- range $peer := $public.accessPoints }}
              {{- if gt $peerIndex 0 }},{{ end }}
              { "address": {{ $peer.address | toJson }}, "port": {{ $peer.port }}, "name": {{ $peer.name | toJson }} }
              {{- $peerIndex = add1 $peerIndex }}
            {{- end }}
            ],
            "advertise": {{ $public.advertise | default false | toJson }}
          }
          {{- $publicIndex = add1 $publicIndex }}
        {{- end }}
      {{- end }}],
      "useLedgerAfterSlot": {{ .Values.topology.useLedgerAfterSlot | int }}
    }
{{- end }}
