apiVersion: v2
name: balius
description: Balius server
version: 0.0.4
appVersion: "0.0.1"

sources:
  - https://github.com/demeter-run/ext-balius

maintainers:
  - name: aurora
    email: aurora@blinklabs.io
  - name: overcookedpanda
    email: overcookedpanda@blinklabs.io
  - name: verbotenj
    email: verbotenj@blinklabs.io
  - name: wolf31o2
    email: wolf31o2@blinklabs.io
