{{- if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels: {{ include "tx-submit-api.selectorLabels" . | nindent 4 }}
  name: {{ include "tx-submit-api.fullname" . }}
spec:
  ports:
  - name: api
    port: {{ .Values.service.apiPort }}
    protocol: TCP
    targetPort: 8090
  - name: metrics
    port: {{ .Values.service.metricsPort }}
    protocol: TCP
    targetPort: 8081
  selector: {{ include "tx-submit-api.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
