apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dolos.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  dolos.toml: |
    [upstream]
    {{- if eq .Values.network "mainnet" }}
    network_magic = 764824073
    {{- else if eq .Values.network "preprod" }}
    network_magic = 1
    {{- else if eq .Values.network "preview" }}
    network_magic = 2
    {{- end }}

    {{- if .Values.dolos.peerAddress }}
    peer_address = "{{ .Values.peerAddress }}"
    {{- if eq .Values.network "mainnet" }}
    is_testnet = false
    {{- else }}
    is_testnet = true
    {{- end }}
    {{- else if eq .Values.network "mainnet" }}
    peer_address = "backbone.{{ .Values.network }}.cardanofoundation.org:3001"
    is_testnet = false
    {{- else }}
    peer_address = "{{ .Values.network }}-node.play.dev.cardano.org:3001"
    is_testnet = true
    {{- end }}

    [storage]
    version = "v1"
    path = "/var/data/{{ .Values.network }}/db"
    wal_size = 1000

    [genesis]
    byron_path = "/etc/genesis/{{ .Values.network }}/byron.json"
    shelley_path = "/etc/genesis/{{ .Values.network }}/shelley.json"
    alonzo_path = "/etc/genesis/{{ .Values.network }}/alonzo.json"
    conway_path = "/etc/genesis/{{ .Values.network }}/conway.json"

    [sync]
    pull_batch_size = 100

    [submit]
    prune_height = 200

    [mithril]
    aggregator = "https://aggregator.release-{{ .Values.network }}.api.mithril.network/aggregator"
    {{- if eq .Values.network "mainnet" }}
    genesis_key = "5b3139312c36362c3134302c3138352c3133382c31312c3233372c3230372c3235302c3134342c32372c322c3138382c33302c31322c38312c3135352c3230342c31302c3137392c37352c32332c3133382c3139362c3231372c352c31342c32302c35372c37392c33392c3137365d"
    {{- else }}
    genesis_key = "5b3132372c37332c3132342c3136312c362c3133372c3133312c3231332c3230372c3131372c3139382c38352c3137362c3139392c3136322c3234312c36382c3132332c3131392c3134352c31332c3233322c3234332c34392c3232392c322c3234392c3230352c3230352c33392c3233352c34345d"
    {{- end }}

    [serve.grpc]
    listen_address = "[::]:{{ .Values.dolos.ports.grpc }}"
    permissive_cors = true

    [serve.ouroboros]
    listen_path = "/ipc/dolos.socket"
    {{- if eq .Values.network "mainnet" }}
    magic = 764824073
    {{- else if eq .Values.network "preprod" }}
    magic = 1
    {{- else if eq .Values.network "preview" }}
    magic = 2
    {{- end }}

    [serve.minibf]
    listen_address = "[::]:{{ .Values.dolos.ports.minibf }}"

    [logging]
    max_level = "debug"
    include_tokio = false
    include_pallas = false
    include_grpc = true
    include_trp = false
    include_minibf = false
