{{- if .Values.blockProducer.enabled }}
{{- include "dingo.blockProducer.validateKeys" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dingo.fullname" . }}-keys
  labels:
    {{- include "dingo.labels" . | nindent 4 }}
type: Opaque
data:
{{- range .Values.blockProducer.keys }}
  {{ .name }}: {{ dict "type" .type "description" .description "cborHex" .cborHex | toJson | b64enc }}
{{- end }}
{{- end }}
