---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dingo.fullname" . }}
  labels:
    {{- include "dingo.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations: {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
  ports:
    - name: relay
      port: {{ .Values.service.ports.relay }}
      targetPort: {{ .Values.environment.CARDANO_PORT | default .Values.service.ports.relay }}
    - name: private
      port: {{ .Values.service.ports.private }}
      targetPort: {{ .Values.environment.CARDANO_PRIVATE_PORT | default .Values.service.ports.private }}
    - name: metrics
      port: {{ .Values.service.ports.metrics }}
      targetPort: {{ .Values.environment.CARDANO_METRICS_PORT | default .Values.service.ports.metrics }}
{{- if gt (int (default "0" (default .Values.service.ports.utxorpc .Values.environment.DINGO_UTXORPC_PORT))) 0 }}
    - name: utxorpc
      port: {{ .Values.environment.DINGO_UTXORPC_PORT | default .Values.service.ports.utxorpc }}
      targetPort: {{ .Values.environment.DINGO_UTXORPC_PORT | default .Values.service.ports.utxorpc }}
{{- end }}
{{- if gt (int (default "0" (default .Values.service.ports.blockfrost .Values.environment.DINGO_BLOCKFROST_PORT))) 0 }}
    - name: blockfrost
      port: {{ .Values.environment.DINGO_BLOCKFROST_PORT | default .Values.service.ports.blockfrost }}
      targetPort: {{ .Values.environment.DINGO_BLOCKFROST_PORT | default .Values.service.ports.blockfrost }}
{{- end }}
{{- if gt (int (default "0" (default .Values.service.ports.mesh .Values.environment.DINGO_MESH_PORT))) 0 }}
    - name: mesh
      port: {{ .Values.environment.DINGO_MESH_PORT | default .Values.service.ports.mesh }}
      targetPort: {{ .Values.environment.DINGO_MESH_PORT | default .Values.service.ports.mesh }}
{{- end }}
  selector:
    {{- include "dingo.matchLabels" . | nindent 4 }}
