name: publish-cardano-node-helm-chart

on:
  push:
    branches: ['main']
    paths: ['charts/cardano-node/**','.github/workflows/publish-cardano-node-helm-chart.yml']

jobs:
  build-and-push-cardano-node-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
      - name: Package and upload chart
        shell: bash
        env:
          REGISTRY: "ghcr.io"
          REPOSITORY: "${{ github.repository }}"
          TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          USER: "${{ github.repository_owner }}"
        run: |
          rm -rf dist
          mkdir dist
          helm package charts/cardano-node/ -d dist/
          echo "${TOKEN}" | helm registry login "${REGISTRY}" -u "${USER}" --password-stdin
          for file in dist/*; do
            helm push "$file" "oci://${REGISTRY}/${REPOSITORY,,}/charts"
          done
