name: publish-bursa-helm-chart

on:
  push:
    branches: ['main']
    paths: ['charts/bursa/**','.github/workflows/publish-bursa-helm-chart.yml']

jobs:
  build-and-push-bursa-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Package and upload chart
        shell: bash
        env:
          REGISTRY: "ghcr.io"
          REPOSITORY: "${{ github.repository }}"
          TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          USER: "${{ github.repository_owner }}"
        run: |
          rm -rf dist
          mkdir dist
          helm package charts/bursa/ -d dist/
          echo "${TOKEN}" | helm registry login "${REGISTRY}" -u "${USER}" --password-stdin
          for file in dist/*; do
            helm push "$file" "oci://${REGISTRY}/${REPOSITORY,,}/charts"
          done
