{{- if .Values.secret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cardano-node-api.fullname" . }}-tls
type: kubernetes.io/tls
stringData:
  tls.key: {{ .Values.secret.tlsKey | quote }} 
  tls.crt: {{ .Values.secret.tlsCrt | quote }}
{{- end }}
