{{ if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.annotations }}
  annotations: {{ toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  labels:
    app: {{ include "cardano-node-api.fullname" . }}
{{ include "cardano-node-api.labels" . | indent 4 }}
  name: {{ include "cardano-node-api.fullname" . }}
spec:
  ports: {{ toYaml .Values.service.ports | nindent 2 }}
  selector:
    cardano_network: {{ .Values.cardano_network }}
    app.kubernetes.io/name: {{ include "cardano-node-api.name" . }}
  sessionAffinity: ClientIP
  type: {{ .Values.service.type }}
{{- end }}
