apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "txSubmitApiOperator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "txSubmitApiOperator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "txSubmitApiOperator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default .Release.Name }}
      containers:
        - name: main
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ADDR
              value: "0.0.0.0:{{ .Values.metricsPort }}"
            - name: K8S_IN_CLUSTER
              value: "true"
            - name: PROMETHEUS_URL
              value: "{{ .Values.prometheusUrl }}"
            - name: METRICS_DELAY
              value: {{ .Values.metricsDelay | quote }}
            - name: DCU_PER_REQUEST
              value: "mainnet={{ .Values.dcuPerRequest.mainnet }},preprod={{ .Values.dcuPerRequest.preprod }},preview={{ .Values.dcuPerRequest.preview }},vector-testnet={{ .Values.dcuPerRequest.vectorTestnet }}"
            - name: DEFAULT_SUBMITAPI_VERSION
              value: {{ .Values.defaultSubmitApiVersion }}
            - name: API_KEY_SALT
              value: {{ .Values.apiKeySalt | quote }}
            - name: DNS_ZONE
              value: {{ .Values.dnsZone }}
            {{- range .Values.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metricsPort }}
              protocol: TCP
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
